/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoeconomia;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import java.util.HashMap;
/**
 *
 * @author asus
 */
public class Window extends javax.swing.JFrame {
    
    private double a;
    private double b;
    private double c;
    private double d;
    private double e;
    private double f;
    private double m;
    private Graphics g;
    private int diferenciax;
    private int diferenciay;
    private HashMap datos;
    private int corrX;
    private int corrY;
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        this.datos = new HashMap();
        g = this.canvas1.getGraphics();
        this.setTitle("Economía");
        this.corrX = 30;
        this.corrY = 500;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        canvas1.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Gráfica Nueva");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem3.setText("Acerca de...");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IngresarDatos ingD = new IngresarDatos();
        ingD.setModal(true);
        ingD.setLocationByPlatform(false);
        ingD.pack();
        ingD.setVisible(true);
        this.a = ingD.a;
        this.b = ingD.b;
        this.c = ingD.c;
        this.d = ingD.d;
        this.e = ingD.e;
        this.f = ingD.f;
        this.m = ingD.m;
        this.diferenciay = (int)(this.b - 500);
        this.diferenciax = (int)(this.a - 650);
        this.drawCanvas();
        this.curvaDemanda(this.a, this.m);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void curvaDemanda(double x, double m){
        double y = x / m;
        g.setColor(Color.red);
        this.lineaSimple(this.redimX(0), this.redimY(y), this.redimX(x), this.redimY(0));
        g.setColor(Color.black);
    }
    
    private void IngresoTotal(){
        double fy1 = 0;
        double fx1 = 0;
        double fy2 = 0;
        double fx2 = 0;
        double p = this.a / this.m;
        g.setColor(Color.orange);
        for(int x = 2; x <= this.a; x+=2){
            for(int y = 2; y <= this.b; y+=2){
                fx1 = this.a - p * (y - 2);
                fy1 = (x - 2) * fx1;
                fx2 = this.a - p * y;
                fy2 = x * fx2;
                this.lineaSimple(redimX(x-2), redimY(fy1), redimX(x), redimY(fy2));
            }
        }
        g.setColor(Color.black);
    }
    
    private void IngresoMarginal(double y){
        double x = (31 * this.b) / this.a;
        g.setColor(Color.blue);
        this.lineaSimple(this.redimX(0), this.redimY(y), this.redimX(x), this.redimY(0));
        g.setColor(Color.black);
    }
    
    private void lineaSimple(double x1, double y1, double x2, double y2){
        g.drawLine((int)x1, (int)y1, (int)x2, (int)y2);
        System.out.println("x1:" + (int)x1 + " y1:" + (int)y1 + " x2:" + (int)x2 + " y2:" + (int)y2);
    }
    
    private void drawCanvas(){
        // Dibujando el plano de coordenadas
        g.setColor(Color.black);        
        // Dibujando el eje y
        g.drawLine(30, 10, 30, 500);
        // Dibujando el eje x
        g.drawLine(30, 500, 650, 500);
    }
    
    private double redimX(double x){
        return this.corrX + (620 / this.a)*x;
    }
    
    private double redimY(double y){
        return this.corrY - (490 / (this.a/2 * this.b*2))*y;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
