/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoeconomia;

import java.awt.Color;
import java.awt.Dialog;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import java.util.HashMap;
/**
 *
 * @author asus
 */
public class Window extends javax.swing.JFrame {
    
    private double a;
    private double b;
    private double c;
    private double d;
    private double e;
    private double f;
    private double m;
    private Graphics g;
    private int diferenciax;
    private int diferenciay;
    private HashMap datos;
    private int corrX;
    private int corrY;
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        this.datos = new HashMap();
        g = this.canvas1.getGraphics();
        this.setTitle("Economía");
        this.corrX = 50;
        this.corrY = 500;
        
        this.canvas1.addMouseMotionListener(new java.awt.event.MouseMotionListener() {
            @Override
            public void mouseDragged(MouseEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void mouseMoved(MouseEvent e) {
                try{
                    String clave = e.getX()+","+e.getY();
                    if(datos.containsKey(clave)){
                        Dato dato = (Dato)datos.get(clave);
                        jLabel3.setText(Double.toString(dato.Precio));
                        jLabel5.setText(Double.toString(dato.NP));
                        jLabel7.setText(Double.toString(dato.CME));
                        jLabel9.setText(Double.toString(dato.CMG));
                        jLabel11.setText(Double.toString(dato.Img));
                        jLabel12.setText(Double.toString(dato.IT));
                        jLabel14.setText(Double.toString(dato.CT));
                        jLabel16.setText(Double.toString(dato.CEF));
                        jLabel18.setText(Double.toString(dato.GT));
                    }
                } catch(Exception ex){
                    System.out.println(ex.getMessage());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(918, 773));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        canvas1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Graficas", jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Precio");

        jLabel3.setText(" ");

        jLabel4.setText("Cantidad Demandada");

        jLabel5.setText(" ");

        jLabel6.setText("Costo Medio");

        jLabel7.setText(" ");

        jLabel8.setText("Costo Marginal");

        jLabel9.setText(" ");

        jLabel10.setText("Ingreso Marginal");

        jLabel11.setText(" ");

        jLabel1.setText("Ingreso Total");

        jLabel12.setText(" ");

        jLabel13.setText("Costo Total");

        jLabel14.setText(" ");

        jLabel15.setText("Coeficiente de Elasticidad");

        jLabel16.setText(" ");

        jLabel17.setText("Ganancia Total");

        jLabel18.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Gráfica Nueva");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Generar Tabla");
        jMenu1.add(jMenuItem4);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem3.setText("Acerca de...");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IngresarDatos ingD = new IngresarDatos();
        ingD.setModal(true);
        ingD.setLocationByPlatform(false);
        ingD.pack();
        ingD.setVisible(true);
        this.a = ingD.a;
        this.b = ingD.b;
        this.c = ingD.c;
        this.d = ingD.d;
        this.e = ingD.e;
        this.f = ingD.f;
        this.m = ingD.m;
        this.diferenciay = (int)(this.b - 500);
        this.diferenciax = (int)(this.a - 650);
        this.drawCanvas();
        this.curvaDemanda();
        this.curvaIMG();
        this.curvaCMG();
        this.curvaCT();
        this.curvaIT();
        this.curvaCME();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void curvaDemanda(){
        g.setColor(Color.red);
        int y1 = 0;
        int y2 = 0;
        for (int i = 1; i <= (int) this.a; i++){
            y1 = (int)Precio(i - 1);
            y2 = (int)Precio(i);
            this.lineaSimple(redimX(i - 1), redimY(y1), redimX(i), redimY(y2));
        }
        g.setColor(Color.black);
    }
    
    private void curvaIT(){
        g.setColor(Color.YELLOW);
        int y1 = 0;
        int y2 = 0;
        for (int x = 2; x <= (int) this.a; x++){
            y1 = (int)IT(x - 1);
            y2 = (int)IT(x);
            this.lineaSimple(redimX(x - 1), redimY2(y1), redimX(x), redimY2(y2));
        }
        g.setColor(Color.BLACK);
    }
    
    private void curvaIMG(){
        g.setColor(Color.BLUE);
        int y1 = 0;
        int y2 = 0;
        Dato dato;
        for (int x = 2; x <= (int) this.a; x++){
            dato = new Dato();
            y1 = (int)IMG(x - 1, x - 2);
            y2 = (int)IMG(x, x - 1);
            if(y2 < 0)
               break;
            this.lineaSimple(redimX(x - 1), redimY(y1), redimX(x), redimY(y2));
            dato.Precio = this.Precio(x);
            dato.NP = x;
            dato.Img = y2;
            dato.CEF = this.CEF(x);
            dato.IT = this.IT(x);
            dato.CT = this.CT(x);
            dato.GT = this.GT(x);
            dato.CME = this.CME(x);
            dato.CMG = this.CMG(x);
            this.datos.put((int)redimX(x) + "," + (int)redimY(y2), dato);
        }
        g.setColor(Color.BLACK);
    }
    
    private void curvaCMG(){
        g.setColor(Color.GREEN);
        int y1 = 0;
        int y2 = 0;
        for (int x = 2; x <= (int) this.a; x++){
            y1 = (int)CMG(x - 1);
            y2 = (int)CMG(x);
            this.lineaSimple(redimX(x - 1), redimY(y1), redimX(x), redimY(y2));
        }
        g.setColor(Color.BLACK);
    }
    
    private void curvaCME(){
        g.setColor(Color.ORANGE);
        int y1 = 0;
        int y2 = 0;
        for (int x = 2; x <= (int) this.a; x++){
            y1 = (int)CME(x - 1);
            y2 = (int)CME(x);
            this.lineaSimple(redimX(x - 1), redimY(y1), redimX(x), redimY(y2));
        }
        g.setColor(Color.BLACK);
    }
    
    private void curvaCT(){
        g.setColor(Color.MAGENTA);
        int y1 = 0;
        int y2 = 0;
        for (int x = 1; x <= (int) this.a; x++){
            y1 = (int)CT(x - 1);
            y2 = (int)CT(x);
            this.lineaSimple(redimX(x - 1), redimY(y1), redimX(x), redimY(y2));
        }
        g.setColor(Color.BLACK);
    }
    
    private double GT(double x){
        return (Precio(x) * x) - CT(x);
    }
    
    private double Precio(double x){
        return (this.a - x) / this.m;
    }
    
    private double Q(double y){
        return this.a - (y * this.m);
    }
    
    private double IT(double x){
        return x * this.Precio(x);
    }
    
    private double CT(double x){
        return (c * (Math.pow(x,3)) - (d * Math.pow(x,2)) + (e * x) + f);
    }
    
    private double CME(double x){
        return c*(Math.pow(x,2))-(d*x)+(e) + (f/x);
    }
    
    private double CMG(double x){
        return 3*c*(Math.pow(x,2))-2*(d*x)+(e);
    }

    private double IMG(double x1, double x2){
        return (this.IT(x2) - this.IT(x1))/(x2 - x1);
    }
    
    private double CEF(double x){
        return ((x-(x-1))/(Precio(x) - Precio(x-1)))*(Precio(x)/x);
    }
    
    private void lineaSimple(double x1, double y1, double x2, double y2){
        g.drawLine((int)x1, (int)y1, (int)x2, (int)y2);
    }
    
    private void punto(double x, double y){
        g.drawLine((int)x, (int)y, (int)x, (int)y);
    }
    
    private void drawCanvas(){
        // Dibujando el plano de coordenadas
        g.setColor(Color.black);        
        // Dibujando el eje y
        g.drawLine(this.corrX, 10, this.corrX, 500);
        // Dibujando el eje x
        g.drawLine(this.corrX, 500, this.corrX + 650, 500);
        // Etiquetando el eje X
        int intervaloy = 0;
        int intervalox = 0;
        for (int x = 0; x <= (this.corrX + 650); x+=(650/10)){
            String cadena = Integer.toString(intervalox);
            char caracteres[] = cadena.toCharArray();
            g.drawChars(caracteres, 0, caracteres.length, corrX + x, 515);
            intervalox += (int)this.a / 9;
        }
        for (int y = 500; y >= 10; y-=(490/10)){
            String cadena = Integer.toString(intervaloy);
            char caracteres[] = cadena.toCharArray();
            g.drawChars(caracteres, 0, caracteres.length, 10, y);
            intervaloy += (int)this.b / 9;
        }
    }
    
    private double redimX(double x){
        return this.corrX + (620 / this.a)*x;
    }
    
    private double redimY(double y){
        return this.corrY - (490 / this.b)*y;
    }
    
    private double redimY2(double y){
        return this.corrY - (490 / ((this.b/2) * (this.a/2)))*y;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
